# Generated by Django 5.1.4 on 2025-01-01 10:44

from django.db import migrations
from django.contrib.auth.hashers import make_password

def create_superuser_with_profile(apps, schema_editor):
    """
    Create the superuser
    """
    User = apps.get_model('auth', 'User')
    Profile = apps.get_model('profiles', 'Profile')

    superuser, created = User.objects.get_or_create(
        username='admin',
        defaults={
            'is_superuser': True,
            'is_staff': True,
            'email': 'admin@example.com',
            'password': make_password('admin') # Hash password
        }
    )

    if created:
        # Created the associated profile
        Profile.objects.create(user=superuser, bio="Admin Profile")
        print('Superuser with profile created.')
    else:
        print('Superuser already exists.')

class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial')
    ]

    operations = [
        migrations.RunPython(create_superuser_with_profile)
    ]
